os: linux
language: python
sudo: false
python: 3.6
addons:
  apt:
    packages:
        - pandoc
        - libffi-dev
        - libffi6
script:
    - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
