language: python
git:
  depth: 5
matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
    python: '2.7'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.5'
script:
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import optimix; optimix.test()"
- popd
branches:
  only:
  - master
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: 1zpPL8o+AszhHeAbOIBHIBW979TFeHfnfP+8MSTVw8eQwksopz70BamgmmqcRQResnyH9eXw/wl0xmGtxklvSH5q2PW+QsmFPJveoJ1KVDZmW4g1Zt8zQEqen/TC73+d7SlMTf9TlBJBho7lko5NEeAwDSex20O35cnTGDRhYWOpkGbwP9s9Iulc/BQuTWWDPi+INfxCWjsPVzKfhtguKuzYb3VZQlwxb9VKuWUON16u+879CO35McGVXqqdiytLbfmzTjLJiJrI20pNkod9ZiBmzjYrbJeuTtNjAZm7cv5Q+tEdLVXoMJtOb4FgJnLq1p2aWlAb7vcmcjRUk5JymGDKKzOw+0xK7mUJPyMVi677KBD9wmFJ1P02u13y0s9ga/swLV1hyn2iJCgMVlvmEi2pvkSkQlwzvGcZkTmAMM1LhARdP1hS3+ITurxjSTjXZ4sqpFOWwo2zUeEaHjt93reAwrkem5ghj0HQ8vxHDhhx9YFkZxZeULrcveYokg4xQiIGV1fbGwmR9oIH4eMnhbPKiMawQPHO4qKcQBKt6N+/XXUBq35GYPrgqDz8eXP4ZgKhTPzN8FUAKQmnVVms5uYM2iES3j9R1T6SEC6nID8b92gBX14KR8e3yeHpg4wOxX9i/BZ3toRvYkkMdzVgmUOyns9VkBwY05juRmI/OaU=
  on:
    distributions: sdist bdist_wheel
    repo: glimix/optimix
